package is.hotelzargo.presentacion.controller;

public enum Event {
	SHOW_CLIENT_FRAME,
	SHOW_ROOM_FRAME,
	SHOW_EMPLOYEE_FRAME,
	SHOW_BOOK_FRAME,
	SHOW_SHIFT_FRAME,
	SHOW_SERVICES_FRAME,
	
	ADD_CLIENT,
	ADD_SHIFT, 
	DELETE_CLIENT, 
	LIST_CLIENT
}
